import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{flipTheme,initializeTheme,type Theme}from"../../../packages/design-system/theme.js";
import{documents}from"./documents.js";
import{Markdown}from"./Markdown.js";
import"./styles.css";

const categories=[...new Set(documents.map(document=>document.category))];
const fileIds:Record<string,string>={"CURRENT-ARCHITECTURE.md":"current-architecture","SYSTEM-DESIGN.md":"system-design","SIMPLIFIED-DESIGN.md":"simplified-design","ARCHITECTURE.md":"architecture-baseline","ARCHITECTURE-REVIEW.md":"architecture-review","CONTRACT-IMPLEMENTATION.md":"contracts","ECONOMIC-SPECIFICATION.md":"economics","AUTHORIZATION-AND-UPGRADES.md":"authorization","ADVERSARIAL-FLOW.md":"adversarial-flow","PRODUCT-READ-MODEL-AND-ORDERS.md":"read-model","INDEXER-DESIGN.md":"indexer","MARKET-MAKING-AND-TESTNET-PLAN.md":"market-making","MARKET-FLOW-CALIBRATION.md":"calibration","HEDGING-OPERATIONS.md":"hedging","MARKET-LIFECYCLE-PLAYBOOK.md":"market-lifecycle","SCALE-AND-STREAMING.md":"scale","LOCAL-DEVELOPMENT.md":"runbook","BASE-SEPOLIA-DEPLOYMENT.md":"testnet","CLOUDFLARE-DEPLOYMENT.md":"cloudflare","EDGE-AND-ORIGIN-PRIVACY.md":"edge","EXTERNAL-INTEGRATION-INPUTS.md":"external-inputs","PRODUCTION-RELEASE-CHECKLIST.md":"release","VALIDATION-REPORT.md":"validation","LOCAL-READINESS-REVIEW.md":"local-review","SYSTEM-AUDIT-2026-09-10.md":"audit-2026-09-10","SYSTEM-AUDIT-2026-09-09.md":"audit-2026-09-09","UX-AND-INTENT.md":"ux","WALLET-AND-DEPOSITS.md":"wallets","DESIGN-SYSTEM.md":"design-system","DESIGN-RESEARCH-SYNTHESIS.md":"design-research","RFQ-PROTOCOL-RESEARCH.md":"protocol-research"};
function App(){const[selected,setSelected]=useState(documents[0].id),[query,setQuery]=useState(""),[theme,setCurrentTheme]=useState<Theme>(()=>initializeTheme());const normalized=query.trim().toLowerCase();const visible=useMemo(()=>documents.filter(document=>!normalized||`${document.title} ${document.summary} ${document.body}`.toLowerCase().includes(normalized)),[normalized]);const document=documents.find(item=>item.id===selected&&visible.includes(item))??visible[0]??documents[0];
 const navigate=(href:string)=>{const file=href.split("#")[0].split("/").pop()?.toUpperCase();if(file&&fileIds[file]){setQuery("");setSelected(fileIds[file]);window.scrollTo(0,0);}};
 return <div className="manual"><aside><div className="brand"><i>R</i><div><b>RFQ Markets</b><span>Internal manual</span></div></div><input aria-label="Search manual" placeholder="Search all documentation" value={query} onChange={event=>setQuery(event.target.value)}/><nav>{categories.map(category=>{const items=visible.filter(item=>item.category===category);return items.length?<section key={category}><h2>{category}</h2>{items.map(item=><button key={item.id} className={item.id===document.id?"active":""} onClick={()=>setSelected(item.id)}><b>{item.title}</b><span>{item.summary}</span></button>)}</section>:null})}</nav><footer>{visible.length} of {documents.length} manuals</footer></aside><main><header><div><span>INTERNAL · RESTRICTED · NO SECRETS</span><span className="manual-actions"><b>Testnet candidate</b><button className="theme-toggle" aria-label={`Use ${theme==="dark"?"light":"dark"} theme`} onClick={()=>setCurrentTheme(flipTheme(theme))}>{theme==="dark"?"☀":"☾"}</button></span></div><p>This bundle contains architecture and operating details. Publish only behind Cloudflare Access.</p></header><article><div className="document-meta"><span>{document.category}</span><span>Source-controlled manual</span></div><Markdown source={document.body} onNavigate={navigate}/></article></main></div>}
createRoot(document.getElementById("root")!).render(<App/>);
