import React from"react";
import{createRoot}from"react-dom/client";
import"@fontsource-variable/ibm-plex-sans/wght.css";
import"@fontsource/ibm-plex-mono/500.css";
import"./styles.css";

const gates=["Frozen commit and reproducible artifact hashes recorded","Independent RPC quorum provisioned and disagreement drill passed","Approver and hedge keys hardware-backed, rotated and restore-tested","Pyth, Base and Hyperliquid sustained soak within latency/error budgets","Invariant fuzzing and differential economic suite complete","Contract, economic and infrastructure audits remediated","Capped canary limits and named incident owners approved"];

function App(){return <div className="wrap"><header><div><span>INTERNAL · RESTRICTED</span><h1>Operations manual</h1></div><b>Testnet candidate</b></header><main>
  <section><h2>Service map</h2><div className="flow"><i>Gateway</i><i>API / sponsor</i><i>3 approvers</i><i>Base clearing</i><i>Indexer</i><i>Hedge worker</i><i>Hyperliquid</i></div><p>The API is the sole active coordinator. Approvers and the hedge worker are private. Customer accounting remains on Base; SQLite stores operational commitments only.</p></section>
  <section><h2>Launch gates</h2>{gates.map(item=><label key={item}><input type="checkbox" disabled/>{item}</label>)}</section>
  <section className="grid"><article><h2>Incident priority</h2><ol><li>Stop new risk through hedge admission or emergency pause.</li><li>Preserve signed journals and current chain/venue evidence.</li><li>Reconcile Base, indexer, sender and venue state.</li><li>Restore one writer and two independent approvers.</li><li>Resume with reduced caps and record the incident.</li></ol></article><article><h2>Never combine</h2><ul><li>Governance and emergency keys</li><li>Two approver keys on one host</li><li>Hedge authority and Base custody</li><li>Public ingress and signer networks</li><li>Customer ledger and operational journals</li></ul></article></section>
  <section><h2>Market-flow calibration</h2><p>Capture public Coinbase/Binance tape as a stress input, then run the purged walk-forward lab. A candidate remains research-only until it passes multiple holdouts and our own paid RFQ markouts.</p><pre>{`npm run capture:market-flow -- --seconds 86400 --output .local-state/market-flow/day-01.csv\nnpm run calibrate:market-flow -- ../.local-state/market-flow/day-01.csv --output ../.local-state/calibration/day-01.json`}</pre><p>Review the private generated HTML report and <code>MARKET-FLOW-CALIBRATION.md</code>. Never auto-promote weights from a single tape window.</p></section>
  <section><h2>Validated commands</h2><pre>{`npm test\nnpm run smoke:local\nnpm run smoke:reorg\nnpm run smoke:approver-outage\nnpm run smoke:sender-replacement\nnpm run smoke:base-sepolia-iteration-e2e\nnpm run smoke:base-sepolia-iteration-hedge-e2e\nnpm run soak:base-sepolia-iteration`}</pre><p>The full evidence and promotion sequence is in <code>PRODUCTION-RELEASE-CHECKLIST.md</code>. Detailed procedures remain in <code>HEDGING-OPERATIONS.md</code>, <code>BASE-SEPOLIA-DEPLOYMENT.md</code>, <code>RUNBOOK.md</code>, <code>MARKET-FLOW-CALIBRATION.md</code> and <code>VALIDATION-REPORT.md</code>.</p></section>
</main></div>}
createRoot(document.getElementById("root")!).render(<App/>);
