import Fastify from "fastify";
import cors from "@fastify/cors";
import { DatabaseSync } from "node:sqlite";
import { Contract, Interface, JsonRpcProvider, getAddress } from "ethers";

const abi=[
  "event Deposited(address indexed account,uint256 amount)","event Withdrawn(address indexed account,uint256 amount)",
  "event TradeExecuted(bytes32 indexed intentHash,address indexed account,uint8 market,int256 baseDelta,uint256 price,uint256 fee)",
  "event NonceCancelled(address indexed account,uint256 indexed nonce)","event PositionClosed(address indexed account,uint8 indexed market,int256 baseDelta,uint256 price)","event MakerWithdrawn(address indexed recipient,uint256 amount)",
  "event SessionGranted(address indexed account,address indexed session,uint64 validUntil,uint128 maxCumulativeNotional)","event SessionRevoked(address indexed account,address indexed session)",
  "event Liquidated(address indexed account,uint8 market,uint256 closedBase,uint256 penalty,uint256 keeperReward)",
  "event DeficitAbsorbed(address indexed account,uint256 insuranceUsed,uint256 makerUsed,uint256 unresolved)",
  "event EpochAdvanced(uint64 epoch)","event ResolutionStarted(uint64 triggerTime)","event ResolutionPriceReady(uint8 indexed market,uint256 price)","event ResolutionFinalized(uint256 claims,uint256 assets)",
  "function collateralOf(address) view returns(int256)","function positionOf(address,uint8) view returns(int256 size,uint256 entryPrice,int256 lastFundingIndex)",
  "function markets(uint256) view returns(int256 aggregateBase,int256 fundingIndex,uint64 fundingTime,uint64 lastPriceTime,uint256 lastBid,uint256 lastAsk,bool enabled)",
  "function leaderEpoch() view returns(uint64)","function signerSetVersion() view returns(uint64)","function policyVersion() view returns(uint64)","function paused() view returns(bool)","function resolutionRequired() view returns(bool)",
];

export interface IndexerOptions{rpcUrl:string;clearingAddress:string;databasePath:string;startBlock?:number;confirmations?:number;pollMs?:number;corsOrigin?:string}

export function buildIndexer(options:IndexerOptions){
  const app=Fastify({logger:false});app.register(cors,{origin:options.corsOrigin??["http://127.0.0.1:4173","http://127.0.0.1:4174"]});
  const provider=new JsonRpcProvider(options.rpcUrl);const contract=new Contract(options.clearingAddress,abi,provider);const iface=new Interface(abi);const db=new DatabaseSync(options.databasePath);
  db.exec("PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS blocks(number INTEGER PRIMARY KEY,hash TEXT NOT NULL,parent_hash TEXT NOT NULL,timestamp INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS activity(tx_hash TEXT NOT NULL,log_index INTEGER NOT NULL,block_number INTEGER NOT NULL,block_hash TEXT NOT NULL,timestamp INTEGER NOT NULL,kind TEXT NOT NULL,account TEXT,market INTEGER,payload TEXT NOT NULL,PRIMARY KEY(tx_hash,log_index)); CREATE INDEX IF NOT EXISTS activity_account_block ON activity(account,block_number DESC,log_index DESC); CREATE TABLE IF NOT EXISTS accounts(account TEXT PRIMARY KEY,collateral TEXT NOT NULL,btc_size TEXT NOT NULL,btc_entry TEXT NOT NULL,eth_size TEXT NOT NULL,eth_entry TEXT NOT NULL,indexed_block INTEGER NOT NULL,indexed_tx TEXT)");
  let syncing:Promise<void>|undefined;let timer:ReturnType<typeof setInterval>|undefined;let lastError:string|undefined;
  const reset=()=>db.exec("DELETE FROM blocks; DELETE FROM activity; DELETE FROM accounts");
  async function updateAccount(account:string,blockTag:number,txHash?:string){const [collateral,btc,eth]=await Promise.all([contract.collateralOf(account,{blockTag}),contract.positionOf(account,0,{blockTag}),contract.positionOf(account,1,{blockTag})]);db.prepare("INSERT INTO accounts VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(account) DO UPDATE SET collateral=excluded.collateral,btc_size=excluded.btc_size,btc_entry=excluded.btc_entry,eth_size=excluded.eth_size,eth_entry=excluded.eth_entry,indexed_block=excluded.indexed_block,indexed_tx=excluded.indexed_tx").run(account,collateral.toString(),btc.size.toString(),btc.entryPrice.toString(),eth.size.toString(),eth.entryPrice.toString(),blockTag,txHash??null);}
  async function doSync(){
    const head=await provider.getBlockNumber();let row=db.prepare("SELECT number,hash FROM blocks ORDER BY number DESC LIMIT 1").get() as {number:number;hash:string}|undefined;
    if(row){const canonical=await provider.getBlock(row.number);if(!canonical||canonical.hash!==row.hash){reset();row=undefined;}}
    const from=Math.max(options.startBlock??0,(row?.number??((options.startBlock??0)-1))+1);if(from>head)return;
    const logs=await provider.getLogs({address:options.clearingAddress,fromBlock:from,toBlock:head});const affected=new Map<string,{tx:string;block:number}>();
    for(let number=from;number<=head;number++){const block=await provider.getBlock(number);if(block)db.prepare("INSERT OR REPLACE INTO blocks VALUES(?,?,?,?)").run(number,block.hash,block.parentHash,block.timestamp);}
    for(const log of logs){let parsed;try{parsed=iface.parseLog(log);}catch{continue}if(!parsed)continue;const block=db.prepare("SELECT timestamp FROM blocks WHERE number=?").get(log.blockNumber) as {timestamp:number};const account=parsed.args.account?getAddress(parsed.args.account):null;const market=parsed.args.market===undefined?null:Number(parsed.args.market);const payload=JSON.stringify(parsed.args.toObject(),(_,value)=>typeof value==="bigint"?value.toString():value);
      db.prepare("INSERT OR REPLACE INTO activity VALUES(?,?,?,?,?,?,?,?,?)").run(log.transactionHash,log.index,log.blockNumber,log.blockHash,block.timestamp,parsed.name,account,market,payload);if(account)affected.set(account,{tx:log.transactionHash,block:log.blockNumber});
    }
    for(const [account,event] of affected)await updateAccount(account,event.block,event.tx);
  }
  async function sync(){if(syncing)return syncing;syncing=doSync().then(()=>{lastError=undefined}).catch(error=>{lastError=String(error)}).finally(()=>{syncing=undefined});return syncing;}
  const limitFrom=(value:string|undefined,fallback=25)=>{const parsed=Number(value??fallback);return Number.isSafeInteger(parsed)?Math.min(100,Math.max(1,parsed)):fallback;};
  const cursorFrom=(value:string|undefined)=>{const parts=(value??`${Number.MAX_SAFE_INTEGER}:${Number.MAX_SAFE_INTEGER}`).split(":").map(Number);return parts.length===2&&parts.every(Number.isSafeInteger)?parts:null;};
  const finalityBlock=async()=>Math.max((options.startBlock??0)-1,(await provider.getBlockNumber())-(options.confirmations??2));
  app.get("/health",async()=>{await sync();const head=await provider.getBlockNumber();const indexed=(db.prepare("SELECT max(number) value FROM blocks").get() as {value:number|null}).value??((options.startBlock??0)-1);const finalized=Math.max((options.startBlock??0)-1,head-(options.confirmations??2));return {ok:!lastError,indexedBlock:indexed,finalizedBlock:Math.min(indexed,finalized),headBlock:head,lag:head-indexed,error:lastError};});
  app.get("/v1/account/:address",async(request,reply)=>{await sync();let account;try{account=getAddress((request.params as {address:string}).address);}catch{return reply.code(400).send({error:"invalid account"});}const row=db.prepare("SELECT * FROM accounts WHERE account=?").get(account) as Record<string,string|number>|undefined;if(!row)return reply.code(404).send({error:"account not indexed"});return {account,collateral:row.collateral,positions:{BTC:{size:row.btc_size,entryPrice:row.btc_entry},ETH:{size:row.eth_size,entryPrice:row.eth_entry}},indexedBlock:row.indexed_block,indexedTransaction:row.indexed_tx};});
  app.get("/v1/account/:address/activity",async(request,reply)=>{await sync();let account;try{account=getAddress((request.params as {address:string}).address);}catch{return reply.code(400).send({error:"invalid account"});}const query=request.query as {cursor?:string;limit?:string};const cursor=cursorFrom(query.cursor);if(!cursor)return reply.code(400).send({error:"invalid cursor"});const [cursorBlock,cursorLog]=cursor;const limit=limitFrom(query.limit);const rows=db.prepare("SELECT * FROM activity WHERE account=? AND (block_number<? OR (block_number=? AND log_index<?)) ORDER BY block_number DESC,log_index DESC LIMIT ?").all(account,cursorBlock,cursorBlock,cursorLog,limit) as Array<Record<string,string|number>>;const finalized=await finalityBlock();return {items:rows.map(row=>({...row,payload:JSON.parse(String(row.payload)),finality:Number(row.block_number)<=finalized?"finalized":"included"})),nextCursor:rows.length===limit?`${rows[rows.length-1].block_number}:${rows[rows.length-1].log_index}`:null};});
  app.get("/v1/activity",async(request,reply)=>{await sync();const query=request.query as {cursor?:string;limit?:string;kind?:string;market?:string;finalized?:string};const cursor=cursorFrom(query.cursor);if(!cursor)return reply.code(400).send({error:"invalid cursor"});const [cursorBlock,cursorLog]=cursor;const limit=limitFrom(query.limit);const allowedKinds=["Deposited","Withdrawn","NonceCancelled","SessionGranted","SessionRevoked","TradeExecuted","PositionClosed","Liquidated","DeficitAbsorbed","MakerWithdrawn","EpochAdvanced","ResolutionStarted","ResolutionPriceReady","ResolutionFinalized"];
    if(query.kind&&!allowedKinds.includes(query.kind))return reply.code(400).send({error:"invalid activity kind"});const market=query.market===undefined?undefined:Number(query.market);if(market!==undefined&&market!==0&&market!==1)return reply.code(400).send({error:"invalid market"});
    const finalized=await finalityBlock();const clauses=["(block_number<? OR (block_number=? AND log_index<?))"],params:Array<string|number>=[cursorBlock,cursorBlock,cursorLog];if(query.finalized==="true"){clauses.push("block_number<=?");params.push(finalized);}if(query.kind){clauses.push("kind=?");params.push(query.kind);}if(market!==undefined){clauses.push("market=?");params.push(market);}params.push(limit);
    const rows=db.prepare(`SELECT * FROM activity WHERE ${clauses.join(" AND ")} ORDER BY block_number DESC,log_index DESC LIMIT ?`).all(...params) as Array<Record<string,string|number>>;return {items:rows.map(row=>({...row,payload:JSON.parse(String(row.payload)),finality:Number(row.block_number)<=finalized?"finalized":"included"})),nextCursor:rows.length===limit?`${rows[rows.length-1].block_number}:${rows[rows.length-1].log_index}`:null,finalizedBlock:finalized};});
  app.get("/v1/exposure",async(request)=>{await sync();const head=await provider.getBlockNumber();const query=request.query as {finalized?:string};const blockTag=query.finalized==="true"?Math.max(options.startBlock??0,head-(options.confirmations??2)):head;const [btc,eth]=await Promise.all([contract.markets(0,{blockTag}),contract.markets(1,{blockTag})]);return {blockNumber:blockTag,markets:{BTC:{aggregateBase:btc.aggregateBase.toString(),bid:btc.lastBid.toString(),ask:btc.lastAsk.toString()},ETH:{aggregateBase:eth.aggregateBase.toString(),bid:eth.lastBid.toString(),ask:eth.lastAsk.toString()}}};});
  app.get("/v1/risk",async(request)=>{await sync();const stored=db.prepare("SELECT account,collateral,btc_size,eth_size,indexed_block FROM accounts").all() as Array<{account:string;collateral:string;btc_size:string;eth_size:string;indexed_block:number}>;const query=request.query as {finalized?:string};const head=await provider.getBlockNumber(),blockTag=query.finalized==="true"?Math.max(options.startBlock??0,head-(options.confirmations??2)):head;const rows=query.finalized==="true"?await Promise.all(stored.map(async row=>{if(row.indexed_block<=blockTag)return row;const [collateral,btc,eth]=await Promise.all([contract.collateralOf(row.account,{blockTag}),contract.positionOf(row.account,0,{blockTag}),contract.positionOf(row.account,1,{blockTag})]);return {account:row.account,collateral:collateral.toString(),btc_size:btc.size.toString(),eth_size:eth.size.toString(),indexed_block:blockTag};})):stored;const aggregate=(key:"btc_size"|"eth_size")=>{let longBase=0n,shortBase=0n,longAccounts=0,shortAccounts=0;for(const row of rows){const value=BigInt(row[key]);if(value>0n){longBase+=value;longAccounts++;}else if(value<0n){shortBase-=value;shortAccounts++;}}return {longBase:longBase.toString(),shortBase:shortBase.toString(),netBase:(longBase-shortBase).toString(),longAccounts,shortAccounts};};let collateral=0n;for(const row of rows)collateral+=BigInt(row.collateral);return {indexedBlock:blockTag,accountCount:rows.length,totalCollateral:collateral.toString(),markets:{BTC:aggregate("btc_size"),ETH:aggregate("eth_size")}};});
  app.get("/v1/positions",async(request,reply)=>{await sync();const query=request.query as {limit?:string;offset?:string;finalized?:string;market?:string};const limit=limitFrom(query.limit,50),offset=Number(query.offset??0);if(!Number.isSafeInteger(offset)||offset<0)return reply.code(400).send({error:"invalid offset"});if(query.market&&!['BTC','ETH'].includes(query.market))return reply.code(400).send({error:"invalid market"});const stored=db.prepare("SELECT account,collateral,btc_size,btc_entry,eth_size,eth_entry,indexed_block FROM accounts ORDER BY account").all() as Array<Record<string,string|number>>;const head=await provider.getBlockNumber(),blockTag=query.finalized!=="false"?Math.max(options.startBlock??0,head-(options.confirmations??2)):head;
    const snapshots=query.finalized!=="false"?await Promise.all(stored.map(async row=>{if(Number(row.indexed_block)<=blockTag)return {account:String(row.account),collateral:String(row.collateral),positions:{BTC:{size:String(row.btc_size),entryPrice:String(row.btc_entry)},ETH:{size:String(row.eth_size),entryPrice:String(row.eth_entry)}}};const [collateral,btc,eth]=await Promise.all([contract.collateralOf(row.account,{blockTag}),contract.positionOf(row.account,0,{blockTag}),contract.positionOf(row.account,1,{blockTag})]);return {account:String(row.account),collateral:collateral.toString(),positions:{BTC:{size:btc.size.toString(),entryPrice:btc.entryPrice.toString()},ETH:{size:eth.size.toString(),entryPrice:eth.entryPrice.toString()}}};})):stored.map(row=>({account:String(row.account),collateral:String(row.collateral),positions:{BTC:{size:String(row.btc_size),entryPrice:String(row.btc_entry)},ETH:{size:String(row.eth_size),entryPrice:String(row.eth_entry)}}}));
    const open=snapshots.filter(row=>query.market?BigInt(row.positions[query.market as "BTC"|"ETH"].size)!==0n:BigInt(row.positions.BTC.size)!==0n||BigInt(row.positions.ETH.size)!==0n);return {items:open.slice(offset,offset+limit),total:open.length,nextOffset:offset+limit<open.length?offset+limit:null,indexedBlock:blockTag,finality:query.finalized!=="false"?"finalized":"included"};});
  app.get("/v1/protocol",async()=>{await sync();const blockNumber=await provider.getBlockNumber();const [epoch,signerSetVersion,policyVersion,paused,resolutionRequired]=await Promise.all([contract.leaderEpoch(),contract.signerSetVersion(),contract.policyVersion(),contract.paused(),contract.resolutionRequired()]);return {blockNumber,leaderEpoch:epoch.toString(),signerSetVersion:signerSetVersion.toString(),policyVersion:policyVersion.toString(),paused,resolutionRequired};});
  app.addHook("onReady",async()=>{await sync();timer=setInterval(()=>void sync(),options.pollMs??500);timer.unref();});app.addHook("onClose",async()=>{if(timer)clearInterval(timer);await syncing;db.close();});return app;
}
