import {BrowserProvider,Contract,formatUnits,getAddress,parseUnits} from "ethers";
import "./styles.css";

type Eip1193={request(args:{method:string;params?:unknown[]}):Promise<unknown>;on?(event:string,listener:()=>void):void;removeListener?(event:string,listener:()=>void):void};
type AccountView={collateral:bigint;btc:{size:bigint;entryPrice:bigint};eth:{size:bigint;entryPrice:bigint};paused:boolean;resolution:boolean;finalized:boolean;claim:bigint;token:string};
const env=import.meta.env,chainId=BigInt(env.VITE_EXIT_CHAIN_ID??0),address=env.VITE_EXIT_CLEARING_ADDRESS,configured=Boolean(address)&&chainId>0n;
const node=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T,value=(id:string)=>node<HTMLInputElement>(id).value,buttonIds=["refresh","withdraw","cancel","revoke","close","claim"];
const abi=["function usdc() view returns(address)","function oracle() view returns(address)","function collateralOf(address) view returns(int256)","function positionOf(address,uint8) view returns(int256 size,uint256 entryPrice,int256 lastFundingIndex)","function paused() view returns(bool)","function resolutionRequired() view returns(bool)","function resolutionFinalized() view returns(bool)","function resolutionClaim(address) view returns(uint256)","function withdraw(uint256)","function cancelNonce(uint256)","function revokeSession(address)","function closePosition(uint8,bytes) payable","function claimResolution()"];
let contract:Contract|undefined,provider:BrowserProvider|undefined,account:string|undefined,current:AccountView|undefined,busy=false;
const setStatus=(text:string,tone:"neutral"|"error"|"success"="neutral")=>{node("status").textContent=text;node("status").className=tone==="neutral"?"":tone;};
const usd=(amount:bigint)=>`${Number(formatUnits(amount,6)).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} USDC`;
const position=(size:bigint)=>size===0n?"Flat":`${size>0n?"Long":"Short"} ${Number(formatUnits(size<0n?-size:size,18)).toLocaleString(undefined,{maximumFractionDigits:6})}`;
function controls(){for(const id of buttonIds)node<HTMLButtonElement>(id).disabled=!account||busy;node<HTMLButtonElement>("connect").disabled=busy||!configured;node<HTMLButtonElement>("refresh").disabled=!account||busy;node<HTMLButtonElement>("close").disabled=!account||busy||!current?.paused;node<HTMLButtonElement>("claim").disabled=!account||busy||!current?.finalized||current.claim===0n;}
function render(state:AccountView){current=state;node("collateral").textContent=usd(state.collateral);node("claim-value").textContent=usd(state.claim);node("btc-position").textContent=position(state.btc.size);node("btc-entry").textContent=`Entry ${state.btc.size===0n?"—":usd(state.btc.entryPrice)}`;node("eth-position").textContent=position(state.eth.size);node("eth-entry").textContent=`Entry ${state.eth.size===0n?"—":usd(state.eth.entryPrice)}`;const protocol=node("protocol-state");protocol.textContent=state.finalized?"Resolution finalized":state.resolution?"Resolution active":state.paused?"Trading paused":"Protocol active";protocol.className=`pill ${state.paused||state.resolution?"paused":"live"}`;controls();}
async function read(){if(!contract||!account)throw new Error("Connect your wallet first");const [collateral,btc,eth,paused,resolution,finalized,claim,token]=await Promise.all([contract.collateralOf(account),contract.positionOf(account,0),contract.positionOf(account,1),contract.paused(),contract.resolutionRequired(),contract.resolutionFinalized(),contract.resolutionClaim(account),contract.usdc()]);render({collateral:BigInt(collateral),btc:{size:BigInt(btc.size),entryPrice:BigInt(btc.entryPrice)},eth:{size:BigInt(eth.size),entryPrice:BigInt(eth.entryPrice)},paused:Boolean(paused),resolution:Boolean(resolution),finalized:Boolean(finalized),claim:BigInt(claim),token:String(token)});}
async function connect(){if(!configured)throw new Error("This build has no reviewed settlement configuration");const ethereum=(window as unknown as {ethereum?:Eip1193}).ethereum;if(!ethereum)throw new Error("Install or open a browser wallet to continue");provider=new BrowserProvider(ethereum as never);await provider.send("eth_requestAccounts",[]);const network=await provider.getNetwork();if(network.chainId!==chainId){try{await provider.send("wallet_switchEthereumChain",[{chainId:`0x${chainId.toString(16)}`}]);}catch{throw new Error(`Switch your wallet to chain ${chainId}`);}}if(await provider.getCode(getAddress(address))==="0x")throw new Error("The reviewed settlement address has no contract code");const signer=await provider.getSigner();account=await signer.getAddress();contract=new Contract(getAddress(address),abi,signer);node("wallet").textContent=`${account.slice(0,8)}…${account.slice(-6)}`;node("network").textContent=`Connected on chain ${chainId}`;node("connect").textContent="Connected";await read();setStatus("Onchain account state is current.","success");}
async function run(label:string,action:()=>Promise<{wait:()=>Promise<{status:number;blockNumber:number}|null>}>){if(busy)return;busy=true;controls();try{if(!contract)await connect();setStatus(`${label}: confirm the transaction in your wallet.`);const tx=await action(),receipt=await tx.wait();if(receipt?.status!==1)throw new Error("The transaction was not confirmed");await read();setStatus(`${label} confirmed in block ${receipt.blockNumber}.`,"success");}catch(error){setStatus(error instanceof Error?error.message:"Transaction unavailable","error");}finally{busy=false;controls();}}
const bind=(id:string,handler:()=>Promise<unknown>)=>node(id).addEventListener("click",()=>void handler().catch(error=>setStatus(error instanceof Error?error.message:"Action unavailable","error")));
node("deployment").textContent=configured?`Chain ${chainId} · ${getAddress(address)}`:"Deployment configuration missing · transactions disabled";
bind("connect",connect);bind("refresh",async()=>{await read();setStatus("Onchain account state is current.","success");});
bind("withdraw",()=>run("Withdrawal",()=>contract!.withdraw(parseUnits(value("amount"),6))));
bind("cancel",()=>run("Nonce cancellation",()=>contract!.cancelNonce(BigInt(value("nonce")))));
bind("revoke",()=>run("Session revocation",()=>contract!.revokeSession(getAddress(value("session")))));
bind("claim",()=>run("Resolution claim",()=>contract!.claimResolution()));
bind("close",()=>run("Paused position close",async()=>{const proof=value("proof").trim(),market=Number(value("market"));if(!/^0x(?:[0-9a-fA-F]{2})+$/.test(proof))throw new Error("Enter a fresh hex oracle proof");if((market===0?current?.btc.size:current?.eth.size)===0n)throw new Error("The selected position is already flat");const oracle=new Contract(await contract!.oracle(),["function updateFee(bytes) view returns(uint256)"],provider);return contract!.closePosition(market,proof,{value:BigInt(await oracle.updateFee(proof))});}));
const injected=(window as unknown as {ethereum?:Eip1193}).ethereum,reset=()=>{account=undefined;contract=undefined;current=undefined;node("wallet").textContent="Not connected";node("network").textContent="Wallet account or network changed. Reconnect to continue.";node("connect").textContent="Reconnect wallet";for(const id of ["collateral","claim-value","btc-position","eth-position"])node(id).textContent="—";controls();setStatus("Wallet context changed. Reconnect before signing.","error");};injected?.on?.("accountsChanged",reset);injected?.on?.("chainChanged",reset);controls();
