import type {DatabaseSync} from 'node:sqlite';
import {GrossReservationBook,assertGrossReservation,type GrossReservation} from './gross-reservations.js';
export function initializeGrossJournal(database:DatabaseSync){database.exec('CREATE TABLE IF NOT EXISTS gross_reservations(id TEXT PRIMARY KEY,market INTEGER NOT NULL,base_delta TEXT NOT NULL,reduce_only INTEGER NOT NULL,deadline INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS gross_deadlines ON gross_reservations(deadline);CREATE TABLE IF NOT EXISTS gross_migrations(name TEXT PRIMARY KEY);CREATE TABLE IF NOT EXISTS gross_context(name TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS gross_clock(singleton INTEGER PRIMARY KEY CHECK(singleton=1),block INTEGER NOT NULL,timestamp INTEGER NOT NULL,hash TEXT)');}
export function persistGross(database:DatabaseSync,id:string,item:GrossReservation){
 assertGrossReservation(item);const result=database.prepare('INSERT INTO gross_reservations VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET deadline=MAX(deadline,excluded.deadline) WHERE market=excluded.market AND base_delta=excluded.base_delta AND reduce_only=excluded.reduce_only').run(id,item.market,item.baseDelta.toString(),Number(item.reduceOnly),item.deadline);if(result.changes!==1)throw new Error('gross journal input mismatch');
}
export function restoreGross(database:DatabaseSync,book:GrossReservationBook){for(const row of database.prepare('SELECT * FROM gross_reservations').all()){const item=row as {id:string;market:0|1;base_delta:string;reduce_only:number;deadline:number};if(item.reduce_only!==0&&item.reduce_only!==1)throw new Error('invalid gross journal');book.reserve(item.id,{market:item.market,baseDelta:BigInt(item.base_delta),reduceOnly:item.reduce_only===1,deadline:item.deadline});}const clock=database.prepare('SELECT block,timestamp,hash FROM gross_clock WHERE singleton=1').get() as {block:number;timestamp:number;hash:string|null}|undefined;if(clock)book.finalize(clock.block,clock.timestamp,0,clock.hash??undefined);}
export function migrateGross(database:DatabaseSync,name:string,backfill:()=>void){if(database.prepare('SELECT 1 FROM gross_migrations WHERE name=?').get(name))return;database.exec('BEGIN IMMEDIATE');try{backfill();database.prepare('INSERT INTO gross_migrations VALUES(?)').run(name);database.exec('COMMIT');}catch(error){database.exec('ROLLBACK');throw error;}}
export function finalizeGross(database:DatabaseSync|undefined,book:GrossReservationBook,block:number,timestamp:number,hash?:string){
 // Delete only rows the memory book proved expired; crashes can retain extra risk, never omit it.
 const expired=book.finalize(block,timestamp,512,hash);if(database){database.exec('BEGIN IMMEDIATE');try{database.prepare('INSERT INTO gross_clock VALUES(1,?,?,?) ON CONFLICT(singleton) DO UPDATE SET block=excluded.block,timestamp=excluded.timestamp,hash=excluded.hash').run(block,timestamp,book.finalizedHash??null);const remove=database.prepare('DELETE FROM gross_reservations WHERE id=? AND deadline<?');for(const id of expired)remove.run(id,timestamp);database.exec('COMMIT');}catch(error){database.exec('ROLLBACK');throw error;}}
}

export function bindGrossContext(database:DatabaseSync,name:string,value:string){const existing=database.prepare('SELECT value FROM gross_context WHERE name=?').get(name) as {value:string}|undefined;if(existing){if(existing.value!==value)throw new Error('gross journal signing context mismatch');}else database.prepare('INSERT INTO gross_context VALUES(?,?)').run(name,value);}
