import {createHash} from "node:crypto";
import{appendFileSync,readFileSync,existsSync,mkdirSync,renameSync,statSync,writeFileSync}from"node:fs";import{dirname,resolve}from"node:path";import{BinanceNormalizer,CoinbaseNormalizer,csvHeader,toCsv,type NormalizedTrade}from"./market-flow-normalizer.js";

const argument=(name:string,fallback:string)=>{const index=process.argv.indexOf(`--${name}`);return index>=0?process.argv[index+1]??fallback:fallback;};
const seconds=Math.max(5,Number(argument("seconds","300"))),output=resolve(argument("output",`.local-state/market-flow/tape-${Date.now()}.csv`)),requested=new Set(argument("venues","coinbase,binance").split(",")),startedAt=Date.now(),deadline=startedAt+seconds*1_000;
if(!requested.size||[...requested].some(name=>name!=="coinbase"&&name!=="binance"))throw new Error("unsupported capture venue");
if(!Number.isFinite(seconds))throw new Error("invalid capture duration");mkdirSync(dirname(output),{recursive:true});if(existsSync(output)&&statSync(output).size)throw new Error("capture output already exists; use a fresh immutable tape path");writeFileSync(output,csvHeader+"\n");
let buffer:string[]=[],closed=false;const sockets=new Set<WebSocket>(),seen=new Set<string>(),counts={coinbase:0,binance:0},errors:string[]=[],lastIds=new Map<string,bigint>(),sequenceGaps={coinbase:0n,binance:0n};
const flush=()=>{if(buffer.length){appendFileSync(output,buffer.join("\n")+"\n");buffer=[];}};
const snapshot=(completed:boolean)=>({capturedAt:new Date().toISOString(),startedAt:new Date(startedAt).toISOString(),requestedDurationSeconds:seconds,durationSeconds:Math.floor((Date.now()-startedAt)/1_000),completed,output,counts,sequenceGaps:{coinbase:String(sequenceGaps.coinbase),binance:String(sequenceGaps.binance)},errorCount,errors:errors.slice(-20),requestedVenues:[...requested]});
const progress=()=>{const temporary=`${output}.progress.json.tmp`;writeFileSync(temporary,JSON.stringify(snapshot(false),null,2)+"\n");renameSync(temporary,`${output}.progress.json`);};
let errorCount=0;
const recordError=(message:string)=>{errorCount++;errors.push(message);if(errors.length>20)errors.shift();};
const record=(item:NormalizedTrade|undefined)=>{if(!item)return;const key=`${item.venue}:${item.market}:${item.tradeId}`;if(seen.has(key))return;seen.add(key);if(seen.size>100_000)seen.delete(seen.values().next().value!);try{const id=BigInt(item.tradeId),stream=`${item.venue}:${item.market}`,last=lastIds.get(stream);if(last!==undefined&&id>last+1n)sequenceGaps[item.venue]+=id-last-1n;if(last===undefined||id>last)lastIds.set(stream,id);}catch{recordError(`${item.venue}:invalid-trade-id`);}counts[item.venue]++;buffer.push(toCsv(item));if(buffer.length>=1_000)flush();};
function connect(name:"coinbase"|"binance",url:string,subscribe:(socket:WebSocket)=>void,parse:(value:unknown)=>NormalizedTrade|undefined){let attempts=0;const open=()=>{if(closed||Date.now()>=deadline)return;const socket=new WebSocket(url);sockets.add(socket);socket.addEventListener("open",()=>{attempts=0;subscribe(socket);});socket.addEventListener("message",event=>{try{record(parse(JSON.parse(String(event.data))));}catch{recordError(`${name}:parse`);}});socket.addEventListener("error",()=>recordError(`${name}:transport`));socket.addEventListener("close",()=>{sockets.delete(socket);if(!closed)setTimeout(open,Math.min(10_000,250*2**Math.min(5,attempts++))).unref();});};open();}
if(requested.has("coinbase")){const normalizer=new CoinbaseNormalizer();connect("coinbase","wss://ws-feed.exchange.coinbase.com",socket=>socket.send(JSON.stringify({type:"subscribe",product_ids:["BTC-USD","ETH-USD"],channels:["matches","ticker","heartbeat"]})),value=>normalizer.normalize(value));}
if(requested.has("binance")){const normalizer=new BinanceNormalizer();connect("binance","wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade/ethusdt@aggTrade/btcusdt@bookTicker/ethusdt@bookTicker",()=>{},value=>normalizer.normalize(value));}
let ticks=0;const timer=setInterval(()=>{flush();if(++ticks%10===0){progress();process.stdout.write(`\rmarket-flow ${counts.coinbase+counts.binance} trades · coinbase ${counts.coinbase} · binance ${counts.binance}`);}},1_000);timer.unref();
const completed=await new Promise<boolean>(resolve=>{const timeout=setTimeout(()=>resolve(true),seconds*1_000);for(const signal of ["SIGINT","SIGTERM"] as const)process.once(signal,()=>{clearTimeout(timeout);resolve(false);});});closed=true;clearInterval(timer);for(const socket of sockets)socket.close();flush();const summary={...snapshot(completed),tapeSha256:createHash("sha256").update(readFileSync(output)).digest("hex")};writeFileSync(`${output}.summary.json`,JSON.stringify(summary,null,2)+"\n");progress();console.log(`\n${JSON.stringify(summary,null,2)}`);if(!completed||errorCount||[...requested].some(venue=>counts[venue as "coinbase"|"binance"]===0)||sequenceGaps.coinbase||sequenceGaps.binance)process.exitCode=1;
