import {readFileSync} from 'node:fs';
import {JsonRpcProvider,keccak256,getAddress} from 'ethers';
import {validateRuntimeIdentity,type RuntimeIdentity} from './runtime-identity.js';
if(!process.argv[2]||!process.env.RFQ_BASE_SEPOLIA_RPC_URL||!process.env.RFQ_SECONDARY_RPC_URL)throw new Error('Supply a deployment manifest and two independent RPC URLs');
const deployment=JSON.parse(readFileSync(process.argv[2],'utf8'));
if(deployment.chainId!=='84532'||deployment.oracleMode!=='pyth')throw new Error('Runtime observation accepts the Base Sepolia Pyth candidate only');
const contracts=deployment.contracts,identity:RuntimeIdentity={chainId:84532n,clearingAddress:contracts.clearingProxy,tokenAddress:contracts.usdc,oracleAddress:contracts.oracleAdapter,oracleSource:contracts.oracleSource,governance:deployment.governance,emergencyCouncil:deployment.emergencyCouncil,feedIds:deployment.feedIds,approvers:deployment.approvers,implementationAddress:contracts.clearingImplementation,riskMathAddress:contracts.riskMath,signatureVerifierAddress:contracts.signatureVerifier,code:[]};
const primary=new JsonRpcProvider(process.env.RFQ_BASE_SEPOLIA_RPC_URL,undefined,{batchMaxCount:1}),secondary=new JsonRpcProvider(process.env.RFQ_SECONDARY_RPC_URL,undefined,{batchMaxCount:1});
try{const block=await primary.getBlockNumber();for(const address of [...new Set([identity.clearingAddress,identity.tokenAddress,identity.oracleAddress,identity.oracleSource,identity.implementationAddress,identity.riskMathAddress,identity.signatureVerifierAddress].map(getAddress))]){const code=await primary.getCode(address,block);if(code==='0x')throw new Error('Observed runtime identity contains missing code');identity.code.push({address,hash:keccak256(code)});}const checkpoint=await validateRuntimeIdentity(primary,secondary,identity);const {chainId,clearingAddress,tokenAddress,feedIds,...runtimeIdentity}=identity;console.log(JSON.stringify({status:'observed_requires_independent_review',checkpoint,chainId:String(chainId),clearingAddress,tokenAddress,feedIds,runtimeIdentity},null,2));}finally{primary.destroy();secondary.destroy();}
