import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {adaptiveSpread,constructQuote,type AdaptiveSpreadInputs,type Market} from '../packages/shared/src/pricing.js';
test('calibration replays active spread component caps, rounding, mode, latency, basis and confidence',()=>{
 let seed=19;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};
 const rows:AdaptiveSpreadInputs[]=[{},...Array.from({length:1000},(_,i)=>({volatilityBps:random()*2600-100,toxicityScoreBps:random()*13000-100,hedgeCostBps:random()*80-10,hedgeLatencyMs:random()*40000-100,venueBasisBps:random()*1400-700,confidenceBps:random()*700-100,riskMode:(['normal','guarded','reduce_only'] as const)[i%3]})),{volatilityBps:5,toxicityScoreBps:10000,hedgeCostBps:50,venueBasisBps:500,confidenceBps:500}];
 const code="import json,sys;sys.path.insert(0,'simulator');from walk_forward_calibration import Observation,spread,CURRENT_WEIGHTS;rows=json.load(sys.stdin);print(json.dumps([spread(Observation(0,r.get('volatilityBps',0),r.get('toxicityScoreBps',0),r.get('hedgeCostBps',0),r.get('venueBasisBps',0),0,hedge_latency_ms=r.get('hedgeLatencyMs',0),confidence_bps=r.get('confidenceBps',0),risk_mode=r.get('riskMode','normal')),CURRENT_WEIGHTS) for r in rows]))";
 const result=spawnSync('python3',['-c',code],{input:JSON.stringify(rows),encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);const actual=JSON.parse(result.stdout) as number[];assert.equal(actual.length,rows.length);rows.forEach((row,i)=>assert.equal(actual[i],Number(adaptiveSpread(row).totalBps),`spread parity vector ${i}`));
});

test('independent calibration replay matches full integer quote and pending envelope over mixed markets/sides',()=>{
 const records=Array.from({length:1000},(_,i)=>{const market:Market=i%2?'BTC':'ETH',side=i%3?'buy' as const:'sell' as const,price=market==='BTC'?100_000_000_000n:4_000_000_000n;return {request:{market,side,amount:`${100+i}.${(i*17).toString().padStart(6,'0')}`},snapshot:{market,bid:price-1000n,ask:price+1000n,observedAtMs:0},settled:{BTC:BigInt(i-500)*1_000_000_000n,ETH:BigInt(400-i)*100_000_000n},pending:[{market:'BTC' as const,delta:BigInt(i)*1_000_000n},{market:'BTC' as const,delta:-BigInt(i)*2_000_000n},{market:'ETH' as const,delta:BigInt(i%10-5)*1_000_000_000n}],spreadInputs:{volatilityBps:i%200,toxicityScoreBps:i%10000,hedgeCostBps:i%40,hedgeLatencyMs:i%3000,venueBasisBps:i%30-15,confidenceBps:i%20,riskMode:(['normal','guarded','reduce_only'] as const)[i%3]},exactBaseDelta:i%4===0?BigInt(side==='buy'?1:-1)*BigInt(i+1)*10n**13n:undefined};});
 const result=spawnSync('python3',['simulator/live_quote_replay.py'],{input:JSON.stringify(records,(_,value)=>typeof value==='bigint'?value.toString():value),encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);const outputs=JSON.parse(result.stdout) as Array<Record<string,string>>;
 records.forEach((record,i)=>{const spread=adaptiveSpread(record.spreadInputs),quote=constructQuote(record.request,record.snapshot,record.settled,record.pending,0,crypto.randomUUID(),{maxNotional:1_000_000n*1_000_000n,baseSpreadBps:spread.totalBps,feeBps:2n,toleranceBps:8n,spread},record.exactBaseDelta);for(const field of ['notional','delta','baseDelta','expectedPrice','worstPrice','fee','impactCharge'] as const)assert.equal(outputs[i][field],quote[field].toString(),`quote parity ${i} ${field}`);});
});
