import Fastify from "fastify";
import type { ServerResponse } from "node:http";
import { MarketFanout, consumeMarketEvents } from "./fanout.js";
import { MarketHistory, type HistoryMarket } from "./history.js";
import {ConnectionBudget} from '../../../packages/shared/src/connection-budget.js';

export interface GatewayOptions {upstreamUrl:string;corsOrigin?:string;fetchImpl?:typeof fetch;reconnectMinMs?:number;reconnectMaxMs?:number;maxBufferedBytes?:number;historyCapacity?:number;historySampleIntervalMs?:number;upstreamStallMs?:number;maxConnections?:number;maxConnectionsPerClient?:number}

export function buildGateway(options:GatewayOptions){
  const connections=new ConnectionBudget(options.maxConnections,options.maxConnectionsPerClient);
  const app=Fastify({logger:false}),fanout=new MarketFanout(options.maxBufferedBytes),history=new MarketHistory(options.historyCapacity,options.historySampleIntervalMs),fetchImpl=options.fetchImpl??fetch,corsOrigin=options.corsOrigin??"http://127.0.0.1:4173";let controller:AbortController|undefined,loop:Promise<void>|undefined,heartbeat:ReturnType<typeof setInterval>|undefined,stopped=false,connected=false,lastFrameAtMs=0,lastError:string|undefined,reconnects=0;
  async function run(){let delay=options.reconnectMinMs??100;while(!stopped){controller=new AbortController();let lastProgress=Date.now();const watchdog=setInterval(()=>{if(Date.now()-lastProgress>(options.upstreamStallMs??10_000))controller?.abort();},Math.min(1000,options.upstreamStallMs??10_000));watchdog.unref();try{const response=await fetchImpl(`${options.upstreamUrl}/v1/markets/stream`,{headers:{accept:"text/event-stream"},signal:controller.signal});connected=true;lastError=undefined;delay=options.reconnectMinMs??100;await consumeMarketEvents(response,data=>{lastProgress=lastFrameAtMs=Date.now();history.record(data);fanout.publish(data);});if(!stopped)throw new Error("upstream market stream ended");}catch(error){connected=false;if(stopped)break;lastError=error instanceof Error?error.message:String(error);reconnects++;await new Promise(resolve=>setTimeout(resolve,delay));delay=Math.min(options.reconnectMaxMs??5_000,delay*2);}finally{clearInterval(watchdog);controller=undefined;}}
  }
  app.get("/health",async()=>({ok:connected&&Date.now()-lastFrameAtMs<5_000,upstreamConnected:connected,lastFrameAtMs,lastError:lastError?"upstream_unavailable":undefined,reconnects,connections:connections.status(),fanout:fanout.status(),history:history.status()}));
  app.get<{Querystring:{market?:string;limit?:string}}>("/v1/markets/history",async(request,reply)=>{reply.header("access-control-allow-origin",corsOrigin).header("cache-control","private, max-age=1");const market=request.query.market;if(market!=="BTC"&&market!=="ETH")return reply.code(400).send({error:"market must be BTC or ETH"});const limit=Number(request.query.limit??300);if(!Number.isInteger(limit)||limit<2||limit>1_800)return reply.code(400).send({error:"limit must be an integer between 2 and 1800"});return {market:market as HistoryMarket,points:history.get(market,limit)};});
  app.get("/v1/markets/stream",async(request,reply)=>{const release=connections.acquire(request.ip);if(!release)return reply.code(429).header("retry-after","5").send({error:"stream connection limit reached"});reply.raw.once("close",release);reply.hijack();reply.raw.writeHead(200,{"content-type":"text/event-stream","cache-control":"no-cache, no-transform","connection":"keep-alive","x-accel-buffering":"no","access-control-allow-origin":corsOrigin});const response=reply.raw as ServerResponse,remove=fanout.add({write:chunk=>response.write(chunk),bufferedBytes:()=>response.writableLength,close:()=>response.end()});response.on("close",remove);});
  app.addHook("onReady",async()=>{stopped=false;loop=run();heartbeat=setInterval(()=>fanout.heartbeat(),15_000);heartbeat.unref();});
  app.addHook("onClose",async()=>{stopped=true;controller?.abort();if(heartbeat)clearInterval(heartbeat);fanout.close();await loop;});
  return app;
}
